# Generated by Django 2.2 on 2020-05-20 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='Test',
        ),
    ]
